# Generated by Django 4.2.10 on 2024-03-05 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, unique=True, verbose_name="Назва"),
                ),
                (
                    "name_uk",
                    models.CharField(
                        max_length=150, null=True, unique=True, verbose_name="Назва"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=150, null=True, unique=True, verbose_name="Назва"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name="URL",
                    ),
                ),
            ],
            options={
                "verbose_name": "категорію",
                "verbose_name_plural": "Категорії",
                "db_table": "category",
            },
        ),
        migrations.CreateModel(
            name="CategoryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_main_content",
                    models.BooleanField(default=False, verbose_name="Головний контент"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="categories_images",
                        verbose_name="Зображення",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.categories",
                    ),
                ),
            ],
            options={
                "verbose_name": "фотографію категорії",
                "verbose_name_plural": "Фотографії категорій",
                "db_table": "category_dimages",
            },
        ),
        migrations.CreateModel(
            name="CategoryDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_main_content",
                    models.BooleanField(default=False, verbose_name="Головний контент"),
                ),
                ("description", models.TextField(verbose_name="Опис категорії")),
                (
                    "description_uk",
                    models.TextField(null=True, verbose_name="Опис категорії"),
                ),
                (
                    "description_en",
                    models.TextField(null=True, verbose_name="Опис категорії"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.categories",
                    ),
                ),
            ],
            options={
                "verbose_name": "описи категорії",
                "verbose_name_plural": "Описи категорій",
                "db_table": "category_description",
            },
        ),
    ]
