# Generated by Django 4.2.10 on 2024-03-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, unique=True, verbose_name="Назва"),
                ),
                (
                    "name_uk",
                    models.CharField(
                        max_length=150, null=True, unique=True, verbose_name="Назва"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=150, null=True, unique=True, verbose_name="Назва"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name="URL",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="categories_images",
                        verbose_name="Зображення",
                    ),
                ),
                (
                    "description",
                    models.TextField(null=True, verbose_name="Опис категорії"),
                ),
                (
                    "description_uk",
                    models.TextField(null=True, verbose_name="Опис категорії"),
                ),
                (
                    "description_en",
                    models.TextField(null=True, verbose_name="Опис категорії"),
                ),
            ],
            options={
                "verbose_name": "категорію",
                "verbose_name_plural": "Категорії",
                "db_table": "category",
            },
        ),
    ]
