# Generated by Django 4.2.10 on 2024-03-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="categories",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="categories_images",
                verbose_name="Зображення",
            ),
        ),
    ]
