# Generated by Django 4.2.10 on 2024-03-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="goods",
            name="preview_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="goods_images",
                verbose_name="Зображення",
            ),
        ),
    ]
