# Generated by Django 4.2.10 on 2024-03-05 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_main_content",
                    models.BooleanField(default=False, verbose_name="Головний контент"),
                ),
                ("text_content", models.TextField(verbose_name="Опис категорії")),
                (
                    "text_content_uk",
                    models.TextField(null=True, verbose_name="Опис категорії"),
                ),
                (
                    "text_content_en",
                    models.TextField(null=True, verbose_name="Опис категорії"),
                ),
                (
                    "category_name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.categories",
                    ),
                ),
            ],
            options={
                "verbose_name": "описи категорії",
                "verbose_name_plural": "Описи категорій",
                "db_table": "category_description",
            },
        ),
    ]
