# Generated by Django 4.2.10 on 2024-03-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_categories_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="categories",
            name="description",
            field=models.TextField(null=True, verbose_name="Опис категорії"),
        ),
    ]
